import type { ClassicStepResponse } from "./types";
import { isTopicAlreadyAnswered } from "./question-dedup";

/** Full ward-round history → case presentation script */
export const CLASSIC_FLOW: Omit<ClassicStepResponse, "workingDifferentials" | "missingCritical">[] = [
  {
    nextStep: "hpi_onset",
    sectionLabel: "History of Presenting Complaint",
    question: "When did the presenting complaint start?",
    inputType: "chips",
    options: ["Today", "1–3 days ago", "4–7 days ago", "Weeks", "Months", "Years"],
    allowCustom: true,
    fieldKey: "hpi_onset",
    category: "hpi",
    reasonForAsking: "Opening the HPI — onset is how you begin presenting to your consultant.",
  },
  {
    nextStep: "hpi_progression",
    sectionLabel: "History of Presenting Complaint",
    question: "How has it progressed since onset?",
    inputType: "chips",
    options: ["Improving", "Worsening", "Static", "Fluctuating", "Stepwise decline"],
    allowCustom: true,
    fieldKey: "hpi_progression",
    category: "hpi",
    reasonForAsking: "Progression helps characterize the illness course in your presentation.",
  },
  {
    nextStep: "hpi_character",
    sectionLabel: "History of Presenting Complaint",
    question: "Describe the symptom (character, site, radiation if applicable)?",
    inputType: "text",
    allowCustom: true,
    fieldKey: "hpi_character",
    category: "hpi",
    reasonForAsking: "Describe what the patient feels — use their words in your case presentation.",
  },
  {
    nextStep: "hpi_associated",
    sectionLabel: "Associated symptoms",
    question: "Associated symptoms?",
    inputType: "multiselect",
    options: ["Fever", "Nausea", "Vomiting", "Weight loss", "Night sweats", "Loss of appetite", "None"],
    allowCustom: true,
    fieldKey: "hpi_associated",
    category: "hpi",
    reasonForAsking: "Associated symptoms complete the presenting illness story.",
  },
  {
    nextStep: "hpi_aggravating",
    sectionLabel: "Aggravating / relieving factors",
    question: "What makes it better or worse?",
    inputType: "text",
    allowCustom: true,
    fieldKey: "hpi_aggravating",
    category: "hpi",
    reasonForAsking: "Aggravating and relieving factors are standard in a full HPI.",
  },
  {
    nextStep: "pmh",
    sectionLabel: "Past medical history",
    question: "Past medical & surgical history?",
    inputType: "multiselect",
    options: ["Diabetes", "Hypertension", "Asthma", "Heart disease", "Previous surgery", "None significant"],
    allowCustom: true,
    fieldKey: "pmh",
    category: "pmh",
    reasonForAsking: "PMH is essential in every ward-round presentation.",
  },
  {
    nextStep: "drugs",
    sectionLabel: "Drug history",
    question: "Current medications and allergies?",
    inputType: "text",
    allowCustom: true,
    fieldKey: "drugs",
    category: "drugs",
    reasonForAsking: "Drug history including allergies must be in your case report.",
  },
  {
    nextStep: "family",
    sectionLabel: "Family history",
    question: "Relevant family history?",
    inputType: "text",
    allowCustom: true,
    fieldKey: "family",
    category: "family",
    reasonForAsking: "Family history can support hereditary or infectious differentials.",
  },
  {
    nextStep: "social",
    sectionLabel: "Social history",
    question: "Social history (smoking, alcohol, occupation, living situation)?",
    inputType: "multiselect",
    options: ["Non-smoker", "Smoker", "Alcohol use", "Student", "Lives alone", "Recent travel"],
    allowCustom: true,
    fieldKey: "social",
    category: "social",
    reasonForAsking: "Social history is part of a complete case presentation.",
  },
  {
    nextStep: "ros",
    sectionLabel: "Review of systems",
    question: "Any other symptoms on systems review?",
    inputType: "multiselect",
    options: [
      "Cardiovascular symptoms",
      "Respiratory symptoms",
      "GI symptoms",
      "Neurological symptoms",
      "Musculoskeletal symptoms",
      "No other symptoms",
    ],
    allowCustom: true,
    fieldKey: "ros",
    category: "ros",
    reasonForAsking: "Brief ROS catches symptoms the patient did not volunteer.",
  },
  {
    nextStep: "exam_general",
    sectionLabel: "Physical examination",
    question: "General examination findings?",
    inputType: "multiselect",
    options: ["Well", "Ill-looking", "Febrile", "Pallor", "No acute distress", "Dehydrated"],
    allowCustom: true,
    fieldKey: "exam_general",
    category: "exam",
    reasonForAsking: "Start your exam section with general appearance.",
  },
  {
    nextStep: "exam_systems",
    sectionLabel: "Physical examination",
    question: "System-specific examination findings?",
    inputType: "text",
    allowCustom: true,
    fieldKey: "exam_systems",
    category: "exam",
    reasonForAsking: "Document focused exam findings for your presentation.",
  },
];

export function getNextClassicStep(answeredKeys: string[]): ClassicStepResponse {
  for (const template of CLASSIC_FLOW) {
    if (!isTopicAlreadyAnswered(template.fieldKey, answeredKeys)) {
      return { ...template };
    }
  }
  return {
    nextStep: "complete",
    sectionLabel: "Complete",
    question: "History complete — generate your case presentation.",
    inputType: "chips",
    options: ["Generate presentation"],
    allowCustom: false,
    fieldKey: "complete",
    category: "complete",
    reasonForAsking: "All history sections collected. Ready to present to your consultant.",
  };
}
