import type { ClinicalStepResponse } from "./types";
import { isTopicAlreadyAnswered } from "./question-dedup";

/**
 * Doctor-style diagnostic workup — fixed order, no AI-shuffled options.
 * Triage → HPI → background → exam → optional investigations → complete
 */
export const CLINICAL_FLOW: Omit<
  ClinicalStepResponse,
  "workingDifferentials" | "missingCritical"
>[] = [
  {
    nextStep: "triage",
    sectionLabel: "1 · Triage",
    question: "Any immediate red flags or signs of instability?",
    inputType: "multiselect",
    options: [
      "Airway compromise",
      "Breathing difficulty / hypoxia",
      "Circulatory shock / hypotension",
      "Altered consciousness (GCS ↓)",
      "Severe pain / distress",
      "High fever with rigors",
      "No red flags — stable",
    ],
    allowCustom: true,
    fieldKey: "triage",
    category: "hpi",
    reasonForAsking: "A doctor always rules out the sick patient first — ABCs and red flags before anything else.",
  },
  {
    nextStep: "onset_progression",
    sectionLabel: "2 · History of presenting complaint",
    question: "Onset, duration, and progression of the main symptom?",
    inputType: "multiselect",
    options: [
      "Sudden / acute onset",
      "Gradual onset",
      "Hours",
      "Days",
      "Weeks or longer",
      "Getting worse",
      "Getting better",
      "Constant",
      "Intermittent",
    ],
    allowCustom: true,
    fieldKey: "onset_progression",
    category: "hpi",
    reasonForAsking: "Timeline separates acute emergencies from chronic conditions and guides urgency.",
  },
  {
    nextStep: "symptom_character",
    sectionLabel: "2 · History of presenting complaint",
    question: "Character, severity, and location of the symptom?",
    inputType: "multiselect",
    options: [
      "Mild",
      "Moderate",
      "Severe",
      "Sharp / stabbing",
      "Dull / aching",
      "Burning",
      "Colicky",
      "Pressure-like",
      "Radiating",
    ],
    allowCustom: true,
    fieldKey: "symptom_character",
    category: "hpi",
    reasonForAsking: "Quality and severity narrow organ systems — e.g. cardiac vs GI vs MSK pain.",
  },
  {
    nextStep: "associated_symptoms",
    sectionLabel: "2 · History of presenting complaint",
    question: "Associated symptoms (positive findings)?",
    inputType: "multiselect",
    options: [
      "Fever",
      "Nausea / vomiting",
      "Diarrhoea",
      "Cough",
      "Dyspnoea",
      "Syncope",
      "Weight loss",
      "Rash",
      "None significant",
    ],
    allowCustom: true,
    fieldKey: "associated_symptoms",
    category: "hpi",
    reasonForAsking: "Associated symptoms build the clinical picture and support or refute differentials.",
  },
  {
    nextStep: "pertinent_negatives",
    sectionLabel: "2 · History of presenting complaint",
    question: "Important negatives — what is the patient NOT reporting?",
    inputType: "multiselect",
    options: [
      "No fever",
      "No chest pain",
      "No shortness of breath",
      "No neurological symptoms",
      "No trauma",
      "No recent travel",
      "No weight loss",
      "None to note",
    ],
    allowCustom: true,
    fieldKey: "pertinent_negatives",
    category: "hpi",
    reasonForAsking: "Pertinent negatives are as important as positives — they rule out dangerous differentials.",
  },
  {
    nextStep: "background",
    sectionLabel: "3 · Background",
    question: "Relevant past history, medications, and allergies?",
    inputType: "multiselect",
    options: [
      "Diabetes",
      "Hypertension",
      "Ischaemic heart disease",
      "Asthma / COPD",
      "Immunosuppression",
      "On anticoagulants",
      "Known drug allergy",
      "Recent hospital admission",
      "None relevant",
    ],
    allowCustom: true,
    fieldKey: "background",
    category: "hpi",
    reasonForAsking: "Comorbidities and drugs change your differential and what you can safely prescribe.",
  },
  {
    nextStep: "exam_general",
    sectionLabel: "4 · Examination",
    question: "General examination — how does the patient look?",
    inputType: "multiselect",
    options: [
      "Well / comfortable",
      "Ill-looking",
      "Febrile",
      "Pallor",
      "Cyanosis",
      "Dehydrated",
      "In respiratory distress",
      "No acute distress",
    ],
    allowCustom: true,
    fieldKey: "exam_general",
    category: "exam",
    reasonForAsking: "First impression at the bedside — sick vs not sick.",
  },
  {
    nextStep: "exam_focused",
    sectionLabel: "4 · Examination",
    question: "Focused examination findings (positives and key negatives)?",
    inputType: "text",
    allowCustom: true,
    fieldKey: "exam_focused",
    category: "exam",
    reasonForAsking: "Targeted exam confirms or excludes your leading differentials.",
  },
  {
    nextStep: "investigations",
    sectionLabel: "5 · Investigations (optional)",
    question: "Which investigations will you order to confirm or exclude your differentials?",
    inputType: "multiselect",
    options: [
      "FBC / CBC",
      "CRP / ESR",
      "U&E / BMP",
      "LFTs",
      "Blood glucose",
      "ECG",
      "Chest X-ray",
      "Urinalysis",
      "Blood cultures",
      "CT scan",
      "Ultrasound",
      "None needed yet",
    ],
    allowCustom: true,
    fieldKey: "investigations",
    category: "investigations",
    reasonForAsking: "Every test should answer a clinical question — skip if not needed.",
  },
];

export function getNextClinicalStep(answeredKeys: string[]): ClinicalStepResponse {
  for (const template of CLINICAL_FLOW) {
    if (!isTopicAlreadyAnswered(template.fieldKey, answeredKeys)) {
      return { ...template, workingDifferentials: [] };
    }
  }
  return {
    nextStep: "complete",
    sectionLabel: "6 · Diagnosis & plan",
    question: "Workup complete — generate diagnosis, differentials, and management plan.",
    inputType: "chips",
    options: ["Generate diagnosis & plan"],
    allowCustom: false,
    fieldKey: "complete",
    category: "complete",
    reasonForAsking: "You have enough data to reason to a diagnosis like you would at the end of a clinic review.",
  };
}
